# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Encoding the Vandegrifter
description: A scholarly project recovering four Gothic fairy tale manuscripts by Fanny Van de Grift Stevenson, an underacknowledged late nineteenth century American writer. 
date: true
baseurl: "/encodingthevandegrifter" # the subpath of your site, e.g. /blog
url: "http://robynpritzker.github.io/encodingthevandegrifter/" # the base hostname & protocol for your site, e.g. http://example.com
author: Dr Robyn Pritzker
twitter: 
  username: robzker


# SEO



lang: en


# Build settings
exclude: README.md
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-roman
  - jekyll-seo-tag
